<?php

namespace Database\Seeders;

use App\Models\Role;
use App\Models\Site;
use Illuminate\Database\Seeder;

class SiteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Site::insert([
            ['url' => 'google.com'],
            ['url' => 'youtube.com'],
            ['url' => 'facebook.com'],
            ['url' => 'laravel.com'],
            ['url' => 'yahoo.com'],
            ['url' => 'amazon.com'],
            ['url' => 'wikipedia.org'],
            ['url' => 'google.co.in'],
            ['url' => 'twitter.com'],
            ['url' => 'qq.com'],
            ['url' => 'live.com'],
            ['url' => 'taobao.com'],
            ['url' => 'bing.com'],
            ['url' => 'google.co.jp'],
            ['url' => 'msn.com'],
            ['url' => 'yahoo.co.jp'],
            ['url' => 'linkedin.com'],
            ['url' => 'sina.com.cn'],
            ['url' => 'instagram.com'],
            ['url' => 'weibo.com'],
            ['url' => 'vk.com'],
            ['url' => 'yandex.ru'],
            ['url' => 'google.de'],
            ['url' => 'google.ru'],
            ['url' => 'hao123.com'],
            ['url' => 'ebay.com'],
            ['url' => 'reddit.com'],
            ['url' => 'google.co.uk'],
            ['url' => 'google.com.br'],
            ['url' => 'mail.ru'],
            ['url' => 't.co'],
            ['url' => 'pinterest.com'],
            ['url' => 'amazon.co.jp'],
            ['url' => 'google.fr'],
            ['url' => 'netflix.com'],
            ['url' => 'gmw.cn'],
            ['url' => 'tmall.com'],
            ['url' => '360.cn'],
            ['url' => 'google.it'],
            ['url' => 'microsoft.com'],
            ['url' => 'onclickads.net'],
            ['url' => 'google.es'],
            ['url' => 'paypal.com'],
            ['url' => 'sohu.com'],
            ['url' => 'wordpress.com'],
            ['url' => 'tumblr.com'],
            ['url' => 'blogspot.com'],
            ['url' => 'imgur.com'],
            ['url' => 'xvideos.com'],
            ['url' => 'google.com.mx'],
            ['url' => 'naver.com'],
            ['url' => 'stackoverflow.com'],
            ['url' => 'apple.com'],
            ['url' => 'chinadaily.com.cn'],
            ['url' => 'fc2.com'],
            ['url' => 'aliexpress.com'],
            ['url' => 'imdb.com'],
            ['url' => 'google.ca'],
            ['url' => 'google.co.kr'],
            ['url' => 'github.com'],
            ['url' => 'ok.ru'],
            ['url' => 'pornhub.com'],
            ['url' => 'google.com.hk'],
            ['url' => 'whatsapp.com'],
            ['url' => 'diply.com'],
            ['url' => 'jd.com'],
            ['url' => 'amazon.de'],
            ['url' => 'google.com.tr'],
            ['url' => 'rakuten.co.jp'],
            ['url' => 'craigslist.org'],
            ['url' => 'office.com'],
            ['url' => 'google.co.id'],
            ['url' => 'kat.cr'],
            ['url' => 'amazon.in'],
            ['url' => 'tianya.cn'],
            ['url' => 'blogger.com'],
            ['url' => 'google.pl'],
            ['url' => 'nicovideo.jp'],
            ['url' => 'alibaba.com'],
            ['url' => 'soso.com'],
            ['url' => 'pixnet.net'],
            ['url' => 'google.com.au'],
            ['url' => 'go.com'],
            ['url' => 'amazon.co.uk'],
            ['url' => 'xhamster.com'],
            ['url' => 'dropbox.com'],
            ['url' => 'google.com.tw'],
            ['url' => 'outbrain.com'],
            ['url' => 'xinhuanet.com'],
            ['url' => 'cntv.cn'],
            ['url' => 'googleusercontent.com'],
            ['url' => 'cnn.com'],
            ['url' => 'ask.com'],
            ['url' => 'coccoc.com'],
            ['url' => 'booking.com'],
            ['url' => 'bbc.co.uk'],
            ['url' => 'popads.net'],
            ['url' => 'youth.cn'],
            ['url' => 'twitch.tv'],
            ['url' => 'wikia.com'],
        ]);
    }
}
